# Node.js with React - Azure Pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Backend (optional — only if you want to install backend dependencies too)
- script: |
    cd backend
    npm install
  displayName: 'Install backend dependencies'

# Frontend build
- script: |
    cd frontend
    npm install
    npm run build
  displayName: 'Install and build frontend'
